Repository crystal-lang-tools/scry, pull requests merged in 2018-05, with the labels that each got.

#92 Check file inside dependency_graph before using it
  spec/scry/completion/dependency_graph_spec.cr
  spec/scry/workspace_spec.cr
  src/scry/completion/dependency_graph.cr
  src/scry/default_crystal_path.cr
  src/scry/workspace.cr
Labels: review required

#98 Reload completion on file changes
  src/scry/completion/dependency_graph.cr
  src/scry/context.cr
  src/scry/workspace.cr
Labels: enhancement, help wanted, review required

#106 Add workspace symbols
  spec/scry/response_spec.cr
  spec/scry/symbol_spec.cr
  src/scry/context.cr
  src/scry/protocol/request_message.cr
  src/scry/protocol/server_capabilities.cr
  src/scry/protocol/workspace_symbol_params.cr
  src/scry/symbol.cr
Labels: enhancement, review required

#95 Support custom main file .scry_main.cr and add some diagnostic fixes
  spec/scry/context_spec.cr
  src/scry/analyzer.cr
  src/scry/context.cr
  src/scry/publish_diagnostic.cr
Labels: review required

#114 Add symbol end_position using end_location
  src/scry/symbol.cr
Labels: enhancement, review required

#116 Do not use File.each_line iterator to ensure Files are closed
  src/scry/completion/dependency_graph.cr
Labels: bug, review required

#119 Use shards build
  README.md
Labels: enhancement, review required

#107 Add hover
  spec/scry/hover_spec.cr
  spec/scry/response_spec.cr
  src/scry/context.cr
  src/scry/hover_provider.cr
  src/scry/implementations.cr
  src/scry/protocol/completion_item.cr
  src/scry/protocol/hover.cr
  src/scry/protocol/markup_content.cr
  src/scry/protocol/response_message.cr
  src/scry/protocol/server_capabilities.cr
  src/scry/tool_helper.cr
Labels: enhancement, review required

#115 Log to LSP client
  spec/scry/client_spec.cr
  spec/scry/response_spec.cr
  src/scry.cr
  src/scry/client.cr
  src/scry/completion/dependency_graph.cr
  src/scry/context.cr
  src/scry/hover_provider.cr
  src/scry/log.cr
  src/scry/message.cr
  src/scry/protocol/log_message_params.cr
  src/scry/protocol/message_type.cr
  src/scry/protocol/notification_message.cr
  src/scry/protocol/response_message.cr
  src/scry/response.cr
  src/scry/workspace.cr
Labels: enhancement, review required

#100 Add class and module name completion
  spec/fixtures/completion/sample.cr
  spec/scry/completion_provider_spec.cr
  src/scry/completion/class_module_context.cr
  src/scry/completion/method_db.cr
  src/scry/completion_provider.cr
Labels: enhancement, review required
